# Generated by Django 4.0 on 2022-01-05 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=10)),
                ('password', models.CharField(db_column='password', max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(db_column='car_name', max_length=20)),
                ('contact', models.CharField(db_column='contact', max_length=20)),
                ('location', models.CharField(db_column='location', max_length=20)),
                ('privacy_agreement', models.BooleanField(db_column='privacy_agreement', default=False)),
                ('status_consulting', models.CharField(db_column='status_consulting', default='상담중', max_length=20)),
                ('status_selling', models.CharField(db_column='status_selling', default='판매예약중', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'buy',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(db_column='car_name', max_length=20)),
                ('contact', models.CharField(db_column='contact', max_length=20)),
                ('location', models.CharField(db_column='location', max_length=20)),
                ('privacy_agreement', models.BooleanField(db_column='privacy_agreement', default=False)),
                ('status_consulting', models.CharField(db_column='status_consulting', default='상담중', max_length=20)),
                ('status_selling', models.CharField(db_column='status_selling', default='판매예약중', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'installment',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(db_column='car_name', max_length=20)),
                ('contact', models.CharField(db_column='contact', max_length=20)),
                ('location', models.CharField(db_column='location', max_length=20)),
                ('privacy_agreement', models.BooleanField(db_column='privacy_agreement', default=False)),
                ('status_consulting', models.CharField(db_column='status_consulting', default='상담중', max_length=20)),
                ('status_selling', models.CharField(db_column='status_selling', default='판매예약중', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sell',
            },
        ),
    ]
