# Generated by Django 4.0 on 2022-01-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='privacy_agreement',
            field=models.BooleanField(db_column='privacy_agreement', default=False),
        ),
    ]
