# Generated by Django 4.0 on 2022-01-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='car_number',
            field=models.CharField(db_column='car_number', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buy',
            name='mileage',
            field=models.CharField(db_column='mileage', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consulting',
            name='car_number',
            field=models.CharField(db_column='car_number', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consulting',
            name='mileage',
            field=models.CharField(db_column='mileage', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='installment',
            name='car_number',
            field=models.CharField(db_column='car_number', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='installment',
            name='mileage',
            field=models.CharField(db_column='mileage', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sell',
            name='car_number',
            field=models.CharField(db_column='car_number', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sell',
            name='mileage',
            field=models.CharField(db_column='mileage', default='', max_length=20),
        ),
    ]
