# Generated by Django 4.0 on 2022-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_consulting_privacy_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=10)),
                ('password', models.CharField(db_column='password', max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.AddField(
            model_name='consulting',
            name='status_consulting',
            field=models.CharField(db_column='status_consulting', default='상담중', max_length=20),
        ),
        migrations.AddField(
            model_name='consulting',
            name='status_selling',
            field=models.CharField(db_column='status_selling', default='판매예약중', max_length=20),
        ),
    ]
